/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
//import aplicacion.TableroData;
import gestor.GestorTableroPanel;
import observador.IObservador;
import test.TableroData;

/**
 *
 * @author HP
 */
public class TableroPanel extends javax.swing.JPanel implements IObservador {

    private TableroData tableroData;
    private GestorTableroPanel gestorTableroPanel;

    public TableroPanel() {
        initComponents();
        this.gestorTableroPanel = new GestorTableroPanel();
    }

    public void cargarInformacion(TableroData tableroData) {
        this.tableroData = tableroData;

    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        dibujarLineas(g);
        dibujarCuadrados(g);
        dibujarPuntos(g);

    }

    private void dibujarPuntos(Graphics g) {
        gestorTableroPanel.dibujarPuntos(g, tableroData.getPuntos(),
                tableroData.getPuntoA(), tableroData.getPuntoB());
    }

    private void dibujarLineas(Graphics g) {
        gestorTableroPanel.dibujarLineas(g, tableroData.getLineas());

    }

    private void dibujarCuadrados(Graphics g) {
        gestorTableroPanel.dibujarCuadrados(g, tableroData.getCuadrados(),
                Double.valueOf(tableroData.getDistanciaPuntos()).intValue());
    }

    @Override
    public void actualizar() {
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
